# Generated by Django 5.2.8 on 2025-11-17 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '__first__'),
        ('hospedagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(verbose_name='Nota')),
                ('comentario', models.TextField(max_length=200, verbose_name='Comentário')),
                ('data_avaliacao', models.DateField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('publicada', models.BooleanField(default=False, verbose_name='Publicada')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospedagens.hospedagem')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['id'],
            },
        ),
    ]
